version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    env_file:
      - .env
  web:
    build:
      dockerfile: ./Dockerfile
    command: sh ./core/run_web.sh
    volumes:
      - ./core:/usr/src/project/core/
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
