# Generated by Django 5.1.1 on 2024-09-30 11:27
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Наименование породы"),
                ),
            ],
            options={
                "verbose_name": "Порода кота",
                "verbose_name_plural": "Породы котов",
            },
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "color",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Черный"),
                            (2, "Белый"),
                            (3, "Рыжий"),
                            (4, "Многоцветный"),
                        ],
                        verbose_name="Цвет",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "description",
                    models.TextField(default="Описания нет.", verbose_name="Описание"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cats",
                        to="showcase.breed",
                        verbose_name="Порода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кот",
                "verbose_name_plural": "Коты",
            },
        ),
    ]
